name: SampleWebApp CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login 
      uses: Azure/docker-login@v1 
      with:
        # Container registry server url
        login-server: eastcanadadevtestacr.azureacr.io
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and Push the Docker image
      run: |
       docker build . -t eastcanadadevtestacr.azureacr.io/samplewebapp:${{ github.sha }}
       docker push eastcanadadevtestacr.azureacr.io/samplewebapp:${{ github.sha }}
